/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalIdRouteImport } from './routes/_authenticated/portal/$id'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AuthenticatedStudioApprovalsRouteImport } from './routes/_authenticated/studio/approvals'
import { Route as AuthenticatedStudioWeeklyRouteImport } from './routes/_authenticated/studio/weekly'
import { Route as AuthenticatedStudioLeadsIndexRouteImport } from './routes/_authenticated/studio/leads/index'
import { Route as AuthenticatedStudioLeadsIdRouteImport } from './routes/_authenticated/studio/leads/$id'
import { Route as AuthenticatedStudioProjectsIndexRouteImport } from './routes/_authenticated/studio/projects/index'
import { Route as AuthenticatedStudioProjectsIdRouteImport } from './routes/_authenticated/studio/projects/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIdRoute = AuthenticatedPortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioApprovalsRoute =
  AuthenticatedStudioApprovalsRouteImport.update({
    id: '/studio/approvals',
    path: '/studio/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioWeeklyRoute =
  AuthenticatedStudioWeeklyRouteImport.update({
    id: '/studio/weekly',
    path: '/studio/weekly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioLeadsIndexRoute =
  AuthenticatedStudioLeadsIndexRouteImport.update({
    id: '/studio/leads/',
    path: '/studio/leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioLeadsIdRoute =
  AuthenticatedStudioLeadsIdRouteImport.update({
    id: '/studio/leads/$id',
    path: '/studio/leads/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioProjectsIndexRoute =
  AuthenticatedStudioProjectsIndexRouteImport.update({
    id: '/studio/projects/',
    path: '/studio/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioProjectsIdRoute =
  AuthenticatedStudioProjectsIdRouteImport.update({
    id: '/studio/projects/$id',
    path: '/studio/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/studio/approvals': typeof AuthenticatedStudioApprovalsRoute
  '/studio/weekly': typeof AuthenticatedStudioWeeklyRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/studio/leads/$id': typeof AuthenticatedStudioLeadsIdRoute
  '/studio/projects/$id': typeof AuthenticatedStudioProjectsIdRoute
  '/studio/leads/': typeof AuthenticatedStudioLeadsIndexRoute
  '/studio/projects/': typeof AuthenticatedStudioProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal': typeof JournalIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/studio/approvals': typeof AuthenticatedStudioApprovalsRoute
  '/studio/weekly': typeof AuthenticatedStudioWeeklyRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/studio/leads/$id': typeof AuthenticatedStudioLeadsIdRoute
  '/studio/projects/$id': typeof AuthenticatedStudioProjectsIdRoute
  '/studio/leads': typeof AuthenticatedStudioLeadsIndexRoute
  '/studio/projects': typeof AuthenticatedStudioProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/_authenticated/portal/$id': typeof AuthenticatedPortalIdRoute
  '/_authenticated/studio/approvals': typeof AuthenticatedStudioApprovalsRoute
  '/_authenticated/studio/weekly': typeof AuthenticatedStudioWeeklyRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated/studio/leads/$id': typeof AuthenticatedStudioLeadsIdRoute
  '/_authenticated/studio/projects/$id': typeof AuthenticatedStudioProjectsIdRoute
  '/_authenticated/studio/leads/': typeof AuthenticatedStudioLeadsIndexRoute
  '/_authenticated/studio/projects/': typeof AuthenticatedStudioProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/process'
    | '/services'
    | '/journal/$slug'
    | '/portfolio/$slug'
    | '/journal/'
    | '/portfolio/'
    | '/portal/$id'
    | '/studio/approvals'
    | '/studio/weekly'
    | '/portal/'
    | '/studio/'
    | '/studio/leads/$id'
    | '/studio/projects/$id'
    | '/studio/leads/'
    | '/studio/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/process'
    | '/services'
    | '/journal/$slug'
    | '/portfolio/$slug'
    | '/journal'
    | '/portfolio'
    | '/portal/$id'
    | '/studio/approvals'
    | '/studio/weekly'
    | '/portal'
    | '/studio'
    | '/studio/leads/$id'
    | '/studio/projects/$id'
    | '/studio/leads'
    | '/studio/projects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/process'
    | '/services'
    | '/journal/$slug'
    | '/portfolio/$slug'
    | '/journal/'
    | '/portfolio/'
    | '/_authenticated/portal/$id'
    | '/_authenticated/studio/approvals'
    | '/_authenticated/studio/weekly'
    | '/_authenticated/portal/'
    | '/_authenticated/studio/'
    | '/_authenticated/studio/leads/$id'
    | '/_authenticated/studio/projects/$id'
    | '/_authenticated/studio/leads/'
    | '/_authenticated/studio/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/$id': {
      id: '/_authenticated/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof AuthenticatedPortalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/approvals': {
      id: '/_authenticated/studio/approvals'
      path: '/studio/approvals'
      fullPath: '/studio/approvals'
      preLoaderRoute: typeof AuthenticatedStudioApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/weekly': {
      id: '/_authenticated/studio/weekly'
      path: '/studio/weekly'
      fullPath: '/studio/weekly'
      preLoaderRoute: typeof AuthenticatedStudioWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/leads/': {
      id: '/_authenticated/studio/leads/'
      path: '/studio/leads'
      fullPath: '/studio/leads/'
      preLoaderRoute: typeof AuthenticatedStudioLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/leads/$id': {
      id: '/_authenticated/studio/leads/$id'
      path: '/studio/leads/$id'
      fullPath: '/studio/leads/$id'
      preLoaderRoute: typeof AuthenticatedStudioLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/projects/': {
      id: '/_authenticated/studio/projects/'
      path: '/studio/projects'
      fullPath: '/studio/projects/'
      preLoaderRoute: typeof AuthenticatedStudioProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/projects/$id': {
      id: '/_authenticated/studio/projects/$id'
      path: '/studio/projects/$id'
      fullPath: '/studio/projects/$id'
      preLoaderRoute: typeof AuthenticatedStudioProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalIdRoute: typeof AuthenticatedPortalIdRoute
  AuthenticatedStudioApprovalsRoute: typeof AuthenticatedStudioApprovalsRoute
  AuthenticatedStudioWeeklyRoute: typeof AuthenticatedStudioWeeklyRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
  AuthenticatedStudioLeadsIdRoute: typeof AuthenticatedStudioLeadsIdRoute
  AuthenticatedStudioProjectsIdRoute: typeof AuthenticatedStudioProjectsIdRoute
  AuthenticatedStudioLeadsIndexRoute: typeof AuthenticatedStudioLeadsIndexRoute
  AuthenticatedStudioProjectsIndexRoute: typeof AuthenticatedStudioProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalIdRoute: AuthenticatedPortalIdRoute,
  AuthenticatedStudioApprovalsRoute: AuthenticatedStudioApprovalsRoute,
  AuthenticatedStudioWeeklyRoute: AuthenticatedStudioWeeklyRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
  AuthenticatedStudioLeadsIdRoute: AuthenticatedStudioLeadsIdRoute,
  AuthenticatedStudioProjectsIdRoute: AuthenticatedStudioProjectsIdRoute,
  AuthenticatedStudioLeadsIndexRoute: AuthenticatedStudioLeadsIndexRoute,
  AuthenticatedStudioProjectsIndexRoute: AuthenticatedStudioProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  JournalSlugRoute: JournalSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
