/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio/$slug'
import { Route as AuthenticatedPortalIndexRouteImport } from './routes/_authenticated/portal/index'
import { Route as AuthenticatedPortalIdRouteImport } from './routes/_authenticated/portal/$id'
import { Route as AuthenticatedStudioIndexRouteImport } from './routes/_authenticated/studio/index'
import { Route as AuthenticatedStudioApprovalsRouteImport } from './routes/_authenticated/studio/approvals'
import { Route as AuthenticatedStudioWeeklyRouteImport } from './routes/_authenticated/studio/weekly'
import { Route as AuthenticatedStudioClientsIndexRouteImport } from './routes/_authenticated/studio/clients/index'
import { Route as AuthenticatedStudioDocumentsIndexRouteImport } from './routes/_authenticated/studio/documents/index'
import { Route as AuthenticatedStudioFinanceIndexRouteImport } from './routes/_authenticated/studio/finance/index'
import { Route as AuthenticatedStudioLeadsIndexRouteImport } from './routes/_authenticated/studio/leads/index'
import { Route as AuthenticatedStudioLeadsIdRouteImport } from './routes/_authenticated/studio/leads/$id'
import { Route as AuthenticatedStudioMaterialsIndexRouteImport } from './routes/_authenticated/studio/materials/index'
import { Route as AuthenticatedStudioMediaIndexRouteImport } from './routes/_authenticated/studio/media/index'
import { Route as AuthenticatedStudioNotificationsIndexRouteImport } from './routes/_authenticated/studio/notifications/index'
import { Route as AuthenticatedStudioProjectsIndexRouteImport } from './routes/_authenticated/studio/projects/index'
import { Route as AuthenticatedStudioProjectsIdRouteImport } from './routes/_authenticated/studio/projects/$id'
import { Route as AuthenticatedStudioQuotationsIndexRouteImport } from './routes/_authenticated/studio/quotations/index'
import { Route as AuthenticatedStudioReportsIndexRouteImport } from './routes/_authenticated/studio/reports/index'
import { Route as AuthenticatedStudioSettingsIndexRouteImport } from './routes/_authenticated/studio/settings/index'
import { Route as AuthenticatedStudioSitesIndexRouteImport } from './routes/_authenticated/studio/sites/index'
import { Route as AuthenticatedStudioTeamIndexRouteImport } from './routes/_authenticated/studio/team/index'
import { Route as AuthenticatedStudioWebsiteIndexRouteImport } from './routes/_authenticated/studio/website/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalIndexRoute =
  AuthenticatedPortalIndexRouteImport.update({
    id: '/portal/',
    path: '/portal/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalIdRoute = AuthenticatedPortalIdRouteImport.update({
  id: '/portal/$id',
  path: '/portal/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioIndexRoute =
  AuthenticatedStudioIndexRouteImport.update({
    id: '/studio/',
    path: '/studio/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioApprovalsRoute =
  AuthenticatedStudioApprovalsRouteImport.update({
    id: '/studio/approvals',
    path: '/studio/approvals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioWeeklyRoute =
  AuthenticatedStudioWeeklyRouteImport.update({
    id: '/studio/weekly',
    path: '/studio/weekly',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioClientsIndexRoute =
  AuthenticatedStudioClientsIndexRouteImport.update({
    id: '/studio/clients/',
    path: '/studio/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioDocumentsIndexRoute =
  AuthenticatedStudioDocumentsIndexRouteImport.update({
    id: '/studio/documents/',
    path: '/studio/documents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioFinanceIndexRoute =
  AuthenticatedStudioFinanceIndexRouteImport.update({
    id: '/studio/finance/',
    path: '/studio/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioLeadsIndexRoute =
  AuthenticatedStudioLeadsIndexRouteImport.update({
    id: '/studio/leads/',
    path: '/studio/leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioLeadsIdRoute =
  AuthenticatedStudioLeadsIdRouteImport.update({
    id: '/studio/leads/$id',
    path: '/studio/leads/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioMaterialsIndexRoute =
  AuthenticatedStudioMaterialsIndexRouteImport.update({
    id: '/studio/materials/',
    path: '/studio/materials/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioMediaIndexRoute =
  AuthenticatedStudioMediaIndexRouteImport.update({
    id: '/studio/media/',
    path: '/studio/media/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioNotificationsIndexRoute =
  AuthenticatedStudioNotificationsIndexRouteImport.update({
    id: '/studio/notifications/',
    path: '/studio/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioProjectsIndexRoute =
  AuthenticatedStudioProjectsIndexRouteImport.update({
    id: '/studio/projects/',
    path: '/studio/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioProjectsIdRoute =
  AuthenticatedStudioProjectsIdRouteImport.update({
    id: '/studio/projects/$id',
    path: '/studio/projects/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioQuotationsIndexRoute =
  AuthenticatedStudioQuotationsIndexRouteImport.update({
    id: '/studio/quotations/',
    path: '/studio/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioReportsIndexRoute =
  AuthenticatedStudioReportsIndexRouteImport.update({
    id: '/studio/reports/',
    path: '/studio/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioSettingsIndexRoute =
  AuthenticatedStudioSettingsIndexRouteImport.update({
    id: '/studio/settings/',
    path: '/studio/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioSitesIndexRoute =
  AuthenticatedStudioSitesIndexRouteImport.update({
    id: '/studio/sites/',
    path: '/studio/sites/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioTeamIndexRoute =
  AuthenticatedStudioTeamIndexRouteImport.update({
    id: '/studio/team/',
    path: '/studio/team/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudioWebsiteIndexRoute =
  AuthenticatedStudioWebsiteIndexRouteImport.update({
    id: '/studio/website/',
    path: '/studio/website/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/studio/approvals': typeof AuthenticatedStudioApprovalsRoute
  '/studio/weekly': typeof AuthenticatedStudioWeeklyRoute
  '/portal/': typeof AuthenticatedPortalIndexRoute
  '/studio/': typeof AuthenticatedStudioIndexRoute
  '/studio/leads/$id': typeof AuthenticatedStudioLeadsIdRoute
  '/studio/projects/$id': typeof AuthenticatedStudioProjectsIdRoute
  '/studio/clients/': typeof AuthenticatedStudioClientsIndexRoute
  '/studio/documents/': typeof AuthenticatedStudioDocumentsIndexRoute
  '/studio/finance/': typeof AuthenticatedStudioFinanceIndexRoute
  '/studio/leads/': typeof AuthenticatedStudioLeadsIndexRoute
  '/studio/materials/': typeof AuthenticatedStudioMaterialsIndexRoute
  '/studio/media/': typeof AuthenticatedStudioMediaIndexRoute
  '/studio/notifications/': typeof AuthenticatedStudioNotificationsIndexRoute
  '/studio/projects/': typeof AuthenticatedStudioProjectsIndexRoute
  '/studio/quotations/': typeof AuthenticatedStudioQuotationsIndexRoute
  '/studio/reports/': typeof AuthenticatedStudioReportsIndexRoute
  '/studio/settings/': typeof AuthenticatedStudioSettingsIndexRoute
  '/studio/sites/': typeof AuthenticatedStudioSitesIndexRoute
  '/studio/team/': typeof AuthenticatedStudioTeamIndexRoute
  '/studio/website/': typeof AuthenticatedStudioWebsiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal': typeof JournalIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/portal/$id': typeof AuthenticatedPortalIdRoute
  '/studio/approvals': typeof AuthenticatedStudioApprovalsRoute
  '/studio/weekly': typeof AuthenticatedStudioWeeklyRoute
  '/portal': typeof AuthenticatedPortalIndexRoute
  '/studio': typeof AuthenticatedStudioIndexRoute
  '/studio/leads/$id': typeof AuthenticatedStudioLeadsIdRoute
  '/studio/projects/$id': typeof AuthenticatedStudioProjectsIdRoute
  '/studio/clients': typeof AuthenticatedStudioClientsIndexRoute
  '/studio/documents': typeof AuthenticatedStudioDocumentsIndexRoute
  '/studio/finance': typeof AuthenticatedStudioFinanceIndexRoute
  '/studio/leads': typeof AuthenticatedStudioLeadsIndexRoute
  '/studio/materials': typeof AuthenticatedStudioMaterialsIndexRoute
  '/studio/media': typeof AuthenticatedStudioMediaIndexRoute
  '/studio/notifications': typeof AuthenticatedStudioNotificationsIndexRoute
  '/studio/projects': typeof AuthenticatedStudioProjectsIndexRoute
  '/studio/quotations': typeof AuthenticatedStudioQuotationsIndexRoute
  '/studio/reports': typeof AuthenticatedStudioReportsIndexRoute
  '/studio/settings': typeof AuthenticatedStudioSettingsIndexRoute
  '/studio/sites': typeof AuthenticatedStudioSitesIndexRoute
  '/studio/team': typeof AuthenticatedStudioTeamIndexRoute
  '/studio/website': typeof AuthenticatedStudioWebsiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/_authenticated/portal/$id': typeof AuthenticatedPortalIdRoute
  '/_authenticated/studio/approvals': typeof AuthenticatedStudioApprovalsRoute
  '/_authenticated/studio/weekly': typeof AuthenticatedStudioWeeklyRoute
  '/_authenticated/portal/': typeof AuthenticatedPortalIndexRoute
  '/_authenticated/studio/': typeof AuthenticatedStudioIndexRoute
  '/_authenticated/studio/leads/$id': typeof AuthenticatedStudioLeadsIdRoute
  '/_authenticated/studio/projects/$id': typeof AuthenticatedStudioProjectsIdRoute
  '/_authenticated/studio/clients/': typeof AuthenticatedStudioClientsIndexRoute
  '/_authenticated/studio/documents/': typeof AuthenticatedStudioDocumentsIndexRoute
  '/_authenticated/studio/finance/': typeof AuthenticatedStudioFinanceIndexRoute
  '/_authenticated/studio/leads/': typeof AuthenticatedStudioLeadsIndexRoute
  '/_authenticated/studio/materials/': typeof AuthenticatedStudioMaterialsIndexRoute
  '/_authenticated/studio/media/': typeof AuthenticatedStudioMediaIndexRoute
  '/_authenticated/studio/notifications/': typeof AuthenticatedStudioNotificationsIndexRoute
  '/_authenticated/studio/projects/': typeof AuthenticatedStudioProjectsIndexRoute
  '/_authenticated/studio/quotations/': typeof AuthenticatedStudioQuotationsIndexRoute
  '/_authenticated/studio/reports/': typeof AuthenticatedStudioReportsIndexRoute
  '/_authenticated/studio/settings/': typeof AuthenticatedStudioSettingsIndexRoute
  '/_authenticated/studio/sites/': typeof AuthenticatedStudioSitesIndexRoute
  '/_authenticated/studio/team/': typeof AuthenticatedStudioTeamIndexRoute
  '/_authenticated/studio/website/': typeof AuthenticatedStudioWebsiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/process'
    | '/services'
    | '/journal/$slug'
    | '/portfolio/$slug'
    | '/journal/'
    | '/portfolio/'
    | '/portal/$id'
    | '/studio/approvals'
    | '/studio/weekly'
    | '/portal/'
    | '/studio/'
    | '/studio/leads/$id'
    | '/studio/projects/$id'
    | '/studio/clients/'
    | '/studio/documents/'
    | '/studio/finance/'
    | '/studio/leads/'
    | '/studio/materials/'
    | '/studio/media/'
    | '/studio/notifications/'
    | '/studio/projects/'
    | '/studio/quotations/'
    | '/studio/reports/'
    | '/studio/settings/'
    | '/studio/sites/'
    | '/studio/team/'
    | '/studio/website/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/process'
    | '/services'
    | '/journal/$slug'
    | '/portfolio/$slug'
    | '/journal'
    | '/portfolio'
    | '/portal/$id'
    | '/studio/approvals'
    | '/studio/weekly'
    | '/portal'
    | '/studio'
    | '/studio/leads/$id'
    | '/studio/projects/$id'
    | '/studio/clients'
    | '/studio/documents'
    | '/studio/finance'
    | '/studio/leads'
    | '/studio/materials'
    | '/studio/media'
    | '/studio/notifications'
    | '/studio/projects'
    | '/studio/quotations'
    | '/studio/reports'
    | '/studio/settings'
    | '/studio/sites'
    | '/studio/team'
    | '/studio/website'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gallery'
    | '/process'
    | '/services'
    | '/journal/$slug'
    | '/portfolio/$slug'
    | '/journal/'
    | '/portfolio/'
    | '/_authenticated/portal/$id'
    | '/_authenticated/studio/approvals'
    | '/_authenticated/studio/weekly'
    | '/_authenticated/portal/'
    | '/_authenticated/studio/'
    | '/_authenticated/studio/leads/$id'
    | '/_authenticated/studio/projects/$id'
    | '/_authenticated/studio/clients/'
    | '/_authenticated/studio/documents/'
    | '/_authenticated/studio/finance/'
    | '/_authenticated/studio/leads/'
    | '/_authenticated/studio/materials/'
    | '/_authenticated/studio/media/'
    | '/_authenticated/studio/notifications/'
    | '/_authenticated/studio/projects/'
    | '/_authenticated/studio/quotations/'
    | '/_authenticated/studio/reports/'
    | '/_authenticated/studio/settings/'
    | '/_authenticated/studio/sites/'
    | '/_authenticated/studio/team/'
    | '/_authenticated/studio/website/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  JournalSlugRoute: typeof JournalSlugRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/': {
      id: '/_authenticated/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof AuthenticatedPortalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/$id': {
      id: '/_authenticated/portal/$id'
      path: '/portal/$id'
      fullPath: '/portal/$id'
      preLoaderRoute: typeof AuthenticatedPortalIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/': {
      id: '/_authenticated/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof AuthenticatedStudioIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/approvals': {
      id: '/_authenticated/studio/approvals'
      path: '/studio/approvals'
      fullPath: '/studio/approvals'
      preLoaderRoute: typeof AuthenticatedStudioApprovalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/weekly': {
      id: '/_authenticated/studio/weekly'
      path: '/studio/weekly'
      fullPath: '/studio/weekly'
      preLoaderRoute: typeof AuthenticatedStudioWeeklyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/clients/': {
      id: '/_authenticated/studio/clients/'
      path: '/studio/clients'
      fullPath: '/studio/clients/'
      preLoaderRoute: typeof AuthenticatedStudioClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/documents/': {
      id: '/_authenticated/studio/documents/'
      path: '/studio/documents'
      fullPath: '/studio/documents/'
      preLoaderRoute: typeof AuthenticatedStudioDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/finance/': {
      id: '/_authenticated/studio/finance/'
      path: '/studio/finance'
      fullPath: '/studio/finance/'
      preLoaderRoute: typeof AuthenticatedStudioFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/leads/': {
      id: '/_authenticated/studio/leads/'
      path: '/studio/leads'
      fullPath: '/studio/leads/'
      preLoaderRoute: typeof AuthenticatedStudioLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/leads/$id': {
      id: '/_authenticated/studio/leads/$id'
      path: '/studio/leads/$id'
      fullPath: '/studio/leads/$id'
      preLoaderRoute: typeof AuthenticatedStudioLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/materials/': {
      id: '/_authenticated/studio/materials/'
      path: '/studio/materials'
      fullPath: '/studio/materials/'
      preLoaderRoute: typeof AuthenticatedStudioMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/media/': {
      id: '/_authenticated/studio/media/'
      path: '/studio/media'
      fullPath: '/studio/media/'
      preLoaderRoute: typeof AuthenticatedStudioMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/notifications/': {
      id: '/_authenticated/studio/notifications/'
      path: '/studio/notifications'
      fullPath: '/studio/notifications/'
      preLoaderRoute: typeof AuthenticatedStudioNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/projects/': {
      id: '/_authenticated/studio/projects/'
      path: '/studio/projects'
      fullPath: '/studio/projects/'
      preLoaderRoute: typeof AuthenticatedStudioProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/projects/$id': {
      id: '/_authenticated/studio/projects/$id'
      path: '/studio/projects/$id'
      fullPath: '/studio/projects/$id'
      preLoaderRoute: typeof AuthenticatedStudioProjectsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/quotations/': {
      id: '/_authenticated/studio/quotations/'
      path: '/studio/quotations'
      fullPath: '/studio/quotations/'
      preLoaderRoute: typeof AuthenticatedStudioQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/reports/': {
      id: '/_authenticated/studio/reports/'
      path: '/studio/reports'
      fullPath: '/studio/reports/'
      preLoaderRoute: typeof AuthenticatedStudioReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/settings/': {
      id: '/_authenticated/studio/settings/'
      path: '/studio/settings'
      fullPath: '/studio/settings/'
      preLoaderRoute: typeof AuthenticatedStudioSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/sites/': {
      id: '/_authenticated/studio/sites/'
      path: '/studio/sites'
      fullPath: '/studio/sites/'
      preLoaderRoute: typeof AuthenticatedStudioSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/team/': {
      id: '/_authenticated/studio/team/'
      path: '/studio/team'
      fullPath: '/studio/team/'
      preLoaderRoute: typeof AuthenticatedStudioTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio/website/': {
      id: '/_authenticated/studio/website/'
      path: '/studio/website'
      fullPath: '/studio/website/'
      preLoaderRoute: typeof AuthenticatedStudioWebsiteIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalIdRoute: typeof AuthenticatedPortalIdRoute
  AuthenticatedStudioApprovalsRoute: typeof AuthenticatedStudioApprovalsRoute
  AuthenticatedStudioWeeklyRoute: typeof AuthenticatedStudioWeeklyRoute
  AuthenticatedPortalIndexRoute: typeof AuthenticatedPortalIndexRoute
  AuthenticatedStudioIndexRoute: typeof AuthenticatedStudioIndexRoute
  AuthenticatedStudioLeadsIdRoute: typeof AuthenticatedStudioLeadsIdRoute
  AuthenticatedStudioProjectsIdRoute: typeof AuthenticatedStudioProjectsIdRoute
  AuthenticatedStudioClientsIndexRoute: typeof AuthenticatedStudioClientsIndexRoute
  AuthenticatedStudioDocumentsIndexRoute: typeof AuthenticatedStudioDocumentsIndexRoute
  AuthenticatedStudioFinanceIndexRoute: typeof AuthenticatedStudioFinanceIndexRoute
  AuthenticatedStudioLeadsIndexRoute: typeof AuthenticatedStudioLeadsIndexRoute
  AuthenticatedStudioMaterialsIndexRoute: typeof AuthenticatedStudioMaterialsIndexRoute
  AuthenticatedStudioMediaIndexRoute: typeof AuthenticatedStudioMediaIndexRoute
  AuthenticatedStudioNotificationsIndexRoute: typeof AuthenticatedStudioNotificationsIndexRoute
  AuthenticatedStudioProjectsIndexRoute: typeof AuthenticatedStudioProjectsIndexRoute
  AuthenticatedStudioQuotationsIndexRoute: typeof AuthenticatedStudioQuotationsIndexRoute
  AuthenticatedStudioReportsIndexRoute: typeof AuthenticatedStudioReportsIndexRoute
  AuthenticatedStudioSettingsIndexRoute: typeof AuthenticatedStudioSettingsIndexRoute
  AuthenticatedStudioSitesIndexRoute: typeof AuthenticatedStudioSitesIndexRoute
  AuthenticatedStudioTeamIndexRoute: typeof AuthenticatedStudioTeamIndexRoute
  AuthenticatedStudioWebsiteIndexRoute: typeof AuthenticatedStudioWebsiteIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalIdRoute: AuthenticatedPortalIdRoute,
  AuthenticatedStudioApprovalsRoute: AuthenticatedStudioApprovalsRoute,
  AuthenticatedStudioWeeklyRoute: AuthenticatedStudioWeeklyRoute,
  AuthenticatedPortalIndexRoute: AuthenticatedPortalIndexRoute,
  AuthenticatedStudioIndexRoute: AuthenticatedStudioIndexRoute,
  AuthenticatedStudioLeadsIdRoute: AuthenticatedStudioLeadsIdRoute,
  AuthenticatedStudioProjectsIdRoute: AuthenticatedStudioProjectsIdRoute,
  AuthenticatedStudioClientsIndexRoute: AuthenticatedStudioClientsIndexRoute,
  AuthenticatedStudioDocumentsIndexRoute:
    AuthenticatedStudioDocumentsIndexRoute,
  AuthenticatedStudioFinanceIndexRoute: AuthenticatedStudioFinanceIndexRoute,
  AuthenticatedStudioLeadsIndexRoute: AuthenticatedStudioLeadsIndexRoute,
  AuthenticatedStudioMaterialsIndexRoute:
    AuthenticatedStudioMaterialsIndexRoute,
  AuthenticatedStudioMediaIndexRoute: AuthenticatedStudioMediaIndexRoute,
  AuthenticatedStudioNotificationsIndexRoute:
    AuthenticatedStudioNotificationsIndexRoute,
  AuthenticatedStudioProjectsIndexRoute: AuthenticatedStudioProjectsIndexRoute,
  AuthenticatedStudioQuotationsIndexRoute:
    AuthenticatedStudioQuotationsIndexRoute,
  AuthenticatedStudioReportsIndexRoute: AuthenticatedStudioReportsIndexRoute,
  AuthenticatedStudioSettingsIndexRoute: AuthenticatedStudioSettingsIndexRoute,
  AuthenticatedStudioSitesIndexRoute: AuthenticatedStudioSitesIndexRoute,
  AuthenticatedStudioTeamIndexRoute: AuthenticatedStudioTeamIndexRoute,
  AuthenticatedStudioWebsiteIndexRoute: AuthenticatedStudioWebsiteIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  JournalSlugRoute: JournalSlugRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
